# Generated by Django 2.2.6 on 2019-11-24 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('user_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100, verbose_name='email address')),
                ('password', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150, unique=True)),
                ('acno', models.CharField(max_length=150, unique=True)),
                ('ifsc', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('acno', models.CharField(max_length=150)),
                ('loan_amount', models.CharField(max_length=150)),
                ('tennure', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('acno', models.CharField(max_length=150, unique=True)),
                ('ifsc', models.CharField(max_length=150)),
                ('balance', models.FloatField(default=10000, max_length=20)),
                ('user', models.ForeignKey(on_delete=False, related_name='User_Account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=150)),
                ('amount', models.FloatField(max_length=150)),
                ('account', models.ForeignKey(null=True, on_delete=False, related_name='User_moneytransfer', to='details.UserAccount')),
                ('amount_received', models.ForeignKey(null=True, on_delete=False, related_name='User_moneyrecievedfrom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=150)),
                ('account', models.ForeignKey(null=True, on_delete=False, related_name='User_moneydeposit', to='details.UserAccount')),
            ],
        ),
    ]
