# Generated by Django 2.2.6 on 2019-11-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='cashback',
            field=models.FloatField(default=0, max_length=150),
        ),
    ]
